[tools]
awscli = "latest"
fzf = "latest"
go = "latest"
helm = "latest"
jj = "latest"
k9s = "latest"
kubectl = "latest"
node = "22"
pipx = "latest"
python = "3.12"
rust = "latest"
uv = "latest"
"github:oraios/serena" = { version = "latest", asset_pattern = "serena_agent-*-py3-none-any.whl" }
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
"npm:task-master-ai" = "latest"
"pipx:git-smart-squash" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
