[tools]
argo = "latest"
ast-grep = "latest"
awscli = { version = "latest", symlink_bins = "true" }
claude = "latest"
dotnet = "latest"
duckdb = "latest"
fzf = "latest"
go = "latest"
helm = "3.18.4"
kustomize = "latest"
jj = "latest"
k9s = "latest"
kubectl = "latest"
node = "22"
pipx = "latest"
python = "3.12"
rust = "latest"
terraform = "latest"
uv = "latest"
"cargo:convfmt" = "latest"
"github:oraios/serena" = { version = "latest", asset_pattern = "serena_agent-*-py3-none-any.whl" }
"go:github.com/dolmen-go/docker-list-context" = "latest"
"npm:ccusage" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
