[tools]
argo = "latest"
ast-grep = "latest"
awscli = { version = "latest", symlink_bins = "true" }
dotnet = "latest"
duckdb = "latest"
fzf = "latest"
go = "latest"
helm = "3.18.4"
kustomize = "latest"
jj = "latest"
k9s = "latest"
kubectl = "latest"
node = "22"
pipx = "latest"
python = "3.12"
rust = "latest"
terraform = "latest"
uv = "latest"
"cargo:convfmt" = "latest"
"go:github.com/dolmen-go/docker-list-context" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@pborck/pi-de" = "latest"
"npm:@tmustier/pi-usage-extension" = "latest"
"npm:lsp-pi" = "latest"
"npm:pi-ask-tool-extension" = "latest"
"npm:pi-mcp-adapter" = "latest"
"npm:pi-md-export" = "latest"
"npm:pi-powerline-footer" = "latest"
"npm:pi-review-loop" = "latest"
"npm:pi-rewind-hook" = "latest"
"npm:pi-skill-palette" = "latest"
"npm:pi-subagents" = "latest"
"npm:pi-web-access" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
